#include "Shader.h"
#include <string>

#include "Renderer/Core/Resources.h"

void Shader::Release()
{
    if (pBlobEnc) {
        pBlobEnc.Reset();
    }
    if (pBlob) {
        pBlob.Reset();
    }
    if (result) {
        result.Reset();
    }

    source.Ptr = nullptr;
    source.Size = 0;
    source.Encoding = 0;
}
DXCRes ShaderCompiler()
{
    DXCRes dxcRes;

    DX_ASSERT(DxcCreateInstance(CLSID_DxcUtils, IID_PPV_ARGS(dxcRes.pUtils.GetAddressOf())));
    DX_ASSERT(DxcCreateInstance(CLSID_DxcCompiler, IID_PPV_ARGS(dxcRes.pCompiler.GetAddressOf())));
    DX_ASSERT(dxcRes.pUtils->CreateDefaultIncludeHandler(dxcRes.pIncludeHandler.GetAddressOf()));
	return dxcRes;
}

void CompileShaderInternal(const GfxDevice& gfxDevice, DXCRes& dxcRes, Shader& shader, const ShaderDesc& shaderDesc)
{
    if (shaderDesc.type == Type::VERTEX)
        shader.type = Type::VERTEX;
    else if (shaderDesc.type == Type::PIXEL)
        shader.type = Type::PIXEL;
    else if (shaderDesc.type == Type::COMPUTE)
        shader.type = Type::COMPUTE;

    const wchar_t* path = shaderDesc.shaderPath;
    const wchar_t* filename = wcsrchr(path, L'/');
    if (filename != nullptr)
    {
        filename++;
    }
    else
    {
        filename = path;
    }

    std::wstring binName = std::wstring(filename) + L".bin";
    std::wstring pdbName = std::wstring(filename) + L".pdb";

    LPCWSTR pszArgs[] =
    {
        shaderDesc.shaderPath,         // Optional shader source file name for error reporting
        // and for PIX shader source view.  
        L"-E", shaderDesc.pEntryPoint,
        L"-T", shaderDesc.pTarget,
        L"-Zs",                         // Enable debug information (slim format)
        //L"-D", L"Raster",   // A single define.
        L"-Fo", binName.c_str(),         // Optional. Stored in the pdb. 
        L"-Fd", pdbName.c_str(),    // The file name of the pdb. This must either be supplied
        // or the autogenerated file name must be used.
        /*L"-Qstrip_reflect",*/             // Strip reflection into a separate blob.
    };

    // open source file
    DX_ASSERT(dxcRes.pUtils->LoadFile(shaderDesc.shaderPath, nullptr, shader.pBlobEnc.GetAddressOf()));
    shader.source.Ptr = shader.pBlobEnc->GetBufferPointer();
    shader.source.Size = shader.pBlobEnc->GetBufferSize();
    shader.source.Encoding = DXC_CP_ACP;

    // compile it with the arguments
    DX_ASSERT(dxcRes.pCompiler->Compile(&shader.source,
        pszArgs,
        _countof(pszArgs),
        dxcRes.pIncludeHandler.Get(),
        IID_PPV_ARGS(&shader.result)));
    ComPtr<IDxcBlobUtf16> pShaderName = nullptr;

    HRESULT resultCode;
    shader.result->GetStatus(&resultCode);
    if (FAILED(resultCode))
    {
        ComPtr<IDxcBlobEncoding> pError;
        if (SUCCEEDED(shader.result->GetErrorBuffer(&pError)) && pError)
        {
            OutputDebugStringA("\n--- SHADER COMPILATION ERROR ---\n");
            printl(Log::LogLevel::Error, "Errors: {}", (const char*)pError->GetBufferPointer());
            OutputDebugStringA("\n--------------------------------\n");
        }
        DX_ASSERT(false);
    }

    DX_ASSERT(shader.result->GetOutput(DXC_OUT_OBJECT, IID_PPV_ARGS(&shader.pBlob), &pShaderName));
    if (shader.pBlob != nullptr)
    {
        FILE* fp = NULL;

        _wfopen_s(&fp, pShaderName->GetStringPointer(), L"wb");
        fwrite(shader.pBlob->GetBufferPointer(), shader.pBlob->GetBufferSize(), 1, fp);
        fclose(fp);
    }

    ComPtr<IDxcBlob> pPDB = nullptr;
    ComPtr<IDxcBlobUtf16> pPDBName = nullptr;
    shader.result->GetOutput(DXC_OUT_PDB, IID_PPV_ARGS(&pPDB), &pPDBName);
    {
        FILE* fp = NULL;

        // Note that if you don't specify -Fd, a pdb name will be automatically generated.
        // Use this file name to save the pdb so that PIX can find it quickly.
        _wfopen_s(&fp, pPDBName->GetStringPointer(), L"wb");
        fwrite(pPDB->GetBufferPointer(), pPDB->GetBufferSize(), 1, fp);
        fclose(fp);
    }
}