add_requires("d3d12-memory-allocator")
add_requires("stb")
add_requires("cgltf")
add_requires("directxshadercompiler")
add_requires("meshoptimizer")
add_requires("imgui docking", {config = { win32 = true, dx12 = true}})
add_requires("luajit")