#include "Shader.h"
#include <string>

#include "Resources.h"

void Shader::Release()
{
    if (_pBlobEnc) {
        _pBlobEnc.Reset();
    }
    if (_pBlob) {
        _pBlob.Reset();
    }
    if (_result) {
        _result.Reset();
    }

    _source.Ptr = nullptr;
    _source.Size = 0;
    _source.Encoding = 0;
}
DXCRes ShaderCompiler()
{
    DXCRes dxcRes;

    DX_ASSERT(DxcCreateInstance(CLSID_DxcUtils, IID_PPV_ARGS(dxcRes._pUtils.GetAddressOf())));
    DX_ASSERT(DxcCreateInstance(CLSID_DxcCompiler, IID_PPV_ARGS(dxcRes._pCompiler.GetAddressOf())));
    DX_ASSERT(dxcRes._pUtils->CreateDefaultIncludeHandler(dxcRes._pIncludeHandler.GetAddressOf()));
	return dxcRes;
}

void CompileShaderInternal(const GfxDevice& gfxDevice, DXCRes& dxcRes, Shader& shader, const ShaderDesc& shaderDesc)
{
    if (shaderDesc._type == Type::VERTEX)
        shader._type = Type::VERTEX;
    else if (shaderDesc._type == Type::PIXEL)
        shader._type = Type::PIXEL;
    else if (shaderDesc._type == Type::COMPUTE)
        shader._type = Type::COMPUTE;

    const wchar_t* path = shaderDesc._shaderPath;
    const wchar_t* filename = wcsrchr(path, L'/');
    if (filename != nullptr)
    {
        filename++;
    }
    else
    {
        filename = path;
    }

    std::wstring binName = std::wstring(filename) + L".bin";
    std::wstring pdbName = std::wstring(filename) + L".pdb";

    LPCWSTR pszArgs[] =
    {
        shaderDesc._shaderPath,         // Optional shader source file name for error reporting
        // and for PIX shader source view.  
        L"-E", shaderDesc._pEntryPoint,
        L"-T", shaderDesc._pTarget,
        L"-Zs",                         // Enable debug information (slim format)
        /*L"-D", L"myTex2DSpace=0",*/   // A single define.
        L"-Fo", binName.c_str(),         // Optional. Stored in the pdb. 
        L"-Fd", pdbName.c_str(),    // The file name of the pdb. This must either be supplied
        // or the autogenerated file name must be used.
        L"-Qstrip_reflect",             // Strip reflection into a separate blob.
    };

    // open source file
    DX_ASSERT(dxcRes._pUtils->LoadFile(shaderDesc._shaderPath, nullptr, shader._pBlobEnc.GetAddressOf()));
    shader._source.Ptr = shader._pBlobEnc->GetBufferPointer();
    shader._source.Size = shader._pBlobEnc->GetBufferSize();
    shader._source.Encoding = DXC_CP_ACP;

    // compile it with the arguments
    DX_ASSERT(dxcRes._pCompiler->Compile(&shader._source,
        pszArgs,
        _countof(pszArgs),
        dxcRes._pIncludeHandler.Get(),
        IID_PPV_ARGS(&shader._result)));
    ComPtr<IDxcBlobUtf16> pShaderName = nullptr;

    HRESULT resultCode;
    shader._result->GetStatus(&resultCode);
    if (FAILED(resultCode))
    {
        ComPtr<IDxcBlobEncoding> pError;
        if (SUCCEEDED(shader._result->GetErrorBuffer(&pError)) && pError)
        {
            OutputDebugStringA("\n--- SHADER COMPILATION ERROR ---\n");
            printl(Log::LogLevel::Error, "Errors: {}", (const char*)pError->GetBufferPointer());
            OutputDebugStringA("\n--------------------------------\n");
        }
        DX_ASSERT(false);
    }

    DX_ASSERT(shader._result->GetOutput(DXC_OUT_OBJECT, IID_PPV_ARGS(&shader._pBlob), &pShaderName));
    if (shader._pBlob != nullptr)
    {
        FILE* fp = NULL;

        _wfopen_s(&fp, pShaderName->GetStringPointer(), L"wb");
        fwrite(shader._pBlob->GetBufferPointer(), shader._pBlob->GetBufferSize(), 1, fp);
        fclose(fp);
    }

    ComPtr<IDxcBlob> pPDB = nullptr;
    ComPtr<IDxcBlobUtf16> pPDBName = nullptr;
    shader._result->GetOutput(DXC_OUT_PDB, IID_PPV_ARGS(&pPDB), &pPDBName);
    {
        FILE* fp = NULL;

        // Note that if you don't specify -Fd, a pdb name will be automatically generated.
        // Use this file name to save the pdb so that PIX can find it quickly.
        _wfopen_s(&fp, pPDBName->GetStringPointer(), L"wb");
        fwrite(pPDB->GetBufferPointer(), pPDB->GetBufferSize(), 1, fp);
        fclose(fp);
    }
}

static void RegisterShader(Resources* resources, const ShaderDesc &shaderDesc, const Shader& shader)
{
    static int shaderCount = -1;
    resources->shaders.push_back(shader);
    resources->shaderParams.push_back(shaderDesc);

    ++shaderCount;
}

Shader CreateShader(const GfxDevice& gfxDevice, Resources* resources, DXCRes& dxcRes, const ShaderDesc& shaderDesc)
{
    Shader shader{};

    CompileShaderInternal(gfxDevice, dxcRes, shader, shaderDesc);

    RegisterShader(resources, shaderDesc, shader);

    return shader;
}
